### PR TITLE
feat: add dates to every files imported ✨

### PR DESCRIPTION
**Pull request by gregorylegarec**

### CODE REVIEW

**Comment by gregorylegarec** [comment]
[Problème de plusieurs fichier avec un même nom pour digiposte](https://trello.com/c/RyT4SnbM/54-probl%C3%A8me-de-plusieurs-fichier-avec-un-m%C3%AAme-nom-pour-digiposte)

**Comment by gregorylegarec** [comment]
@doubleface Any clue about how to fix that ?

**Comment by doubleface** [comment]
@gregorylegarec You can just use module.exports in utils.js and babel won't be needed to run the connector in standalone mode.

**Comment by gregorylegarec** [comment]
@doubleface I eventually improved the standalone command to babelize `index.js` and `utils.js`. It is temporary in a sense that I think we should use `babel-node` in the standalone script in `cozy-konnector-libs`. Does it feel ok to you ?

**Comment by doubleface** [comment]
@gregorylegarec If you want to do temporary code, isn't it better to just use module.exports and then improve cozy-konnector-libs to use babel-cli. Does it break something?

`babel index.js --out-file build/index.js && babel utils.js --out-file build/utils.js && cp konnector-dev-config.json build/ && (cd build && cozy-konnector-standalone)` does not feel ok to me, even for "temporary" code.

**Comment by gregorylegarec** [comment]
@doubleface For me it's better to keep improving the code and target es2015 features in every app and repo, using `module.exports` will never make us improve this part of the code ever. So let's go for babel-node in cozy-konnector-libs 👍

**Comment by gregorylegarec** [comment]
@doubleface I finally fixed the build issues (FYI it was due to ES2015 syntax in cozy-konnector-libs).
Ready to merge if your ok :)

**Pull request merged**
